language: node_js
node_js:
  - "10.14.2"

cache:
  directories:
  - $HOME/.npm

notifications:
  email:
    on_failure: change
    on_success: change

stages:
  - install
  - lint
  - test
  - build


jobs:
  include:
    - stage: install
      script: npm ci

    - stage: lint
      script:
        - npm run affected:lint -- --base=origin/master
        - npm run lint:styles

    - stage: test
      script:
        - npm run affected:test -- --base=origin/master

    - stage: build
      script:
        - npm run affected:build -- --base=origin/master
