language: node_js
node_js:
  - "10.14.2"

cache:
  directories:
  - $HOME/.npm

notifications:
  email:
    on_failure: change
    on_success: change

stages:
  - install
  - lint
  - test
  - build


jobs:
  include:
    - stage: install
      script: npm ci

    - stage: lint
      script:
        - npm run affected:lint -- --base=master --parallel
        - npm run lint:styles

    - stage: test
      script:
        - npm run affected:test -- --base=master

    - stage: build
      script:
        - npm run build:fosdem19:ssr:production
        - sh build-docker-fosdem19.sh
