language: node_js
node_js:
  - "10.14.2"

cache:
  directories:
  - $HOME/.npm

notifications:
  email:
    on_failure: change
    on_success: change

install:
  - npm ci

script:
  - npm run lint:ci
  - npm run test:ci
  - npm run build:fosdem19:ssr:production
  - sh build-docker-fosdem19.sh
