env:
  global:
  - secure: KwaCAhhp3uAY6ptg6i0B92H0D30rIOmbW3cvIs+pfE/GyXSafspWE7HTKZS6nZn9Dx2o4py4rcIvszwBigFeUw03a/2GKHGq+Abs5GHD9qDchZuZTs6tnWQvnh0rrZd5mjWdnufl90OsU2bNRG5zwShdYng1+WpRrRWWvRZUnucwiqmxWaGnXJnZHeV6QKHACIvlPSj4k4dL3JOO0s5Ph9zI+2ZaREFqKwOwz2eP+B/bsyx9QJfxcLx59Op9Gk+FOlYjf5a+9TeAXFYAIjak4YDsoPOPh7HgP9/d2w2t30lmWAa9vmWYNBjrCjYVEBv8ayqPH2A6pJKQxXX4QS8jrB1FUNzuEnZoAN7yo2LZ43TckgAnO3MttUiSAjlZ5fmiBlH05Np/v7QtWAn4atI+zmaMHAnALVW0hxO7cOOgAsybMHTDOly2Lcc/xHqcV4k6ET6+L5Weeae+Hx+97ufFGlephjY7yVuSwQ9lZPJQZrONX12jCu5z0ZCS/HAQ1kGgCTfo6eE+7zWVSgOrE1jYeL2xN9H2eHjZFnHhthrJKbDPj3qNsnsfUYZhwGR1KE26eD+8fzF4GYmN5NPCtGDYSUEC+QW+5P3emP6I65eHYnGbIV1V3wH8ou4qzh6vpu3LkHtOfwjLLMP+SuMGwumowQEVkVPqQvMTouSRYUWYIaM=
  - secure: DNJ+9FZ8/kxzSbryk1lPrYsmP1Tkzxt95xH5YXYLParSKP+y+wgTocaJS+pOGUaufwjSnalTxIE4EGU8FJTbsfA1MQfciSVu9VkbAicWdh6ijadU16eKaVB3pDkdBR5ABsWdX5PkqviYSlI3mSR9gQ7V+Czxij/2Om0YAOSJAyeMM1ntlg+iHPZo5TQWqnTuW33oUv/OoYM0LGMs9SqC/hOzLu6d8MqWokiVZJzYONOlLcILqtjN6o4B2yDcGMehULvR2ceO36u0wpXcvF0wCZtVYE80w5ub4LQ4up3JB15TGqPIqw7UtJoYd/zY78LSmljgUdAhS2QTPairZAwQ4DCdzDQkgyvkc6+ee5Y6sdRpy0OypRVW3+GehKaP+g1ipi0xGquF7LfpkcFCSUfzrJJ4SXLrDcIo/zLhtMOKIGH7ce4y2DzJOzaFXWIbBEgi1EeAFY6lNqH3eSBqV5omOyEiCTx2yFS6hMI6n3OsWPjICA2LFAg2mnHGjvehueWaRp3trvhNXAcYxSZZraibzNLWdR8x9/1LIvgn8y/NuK9Z/kTo9DZVrxXmDvMtqSL1+ookb6Gd1bJpJ2TRoVkEjGsUq9Xl/6ms7p4m1WNkfzJTbgh07DUtd+18lh/jF6UkPBS3zRzCNaS93ZOWuKPCYpya8TUAEtybwMXWj7fBwnM=
  - secure: VZwMiv3o74UFT1lfiu8NNEf3DL0MiexF5AAxNLCJpBKtGdY4zkkgC+m4lo48CKwSv0gWUVCL6+trKdGRYPCFl20malB2em/+Ee/EDf2FXRmELYvMXeuMIPcIMsDnjXQFhCwzcZjzUfm68XHKYznMtEt5zGijPnmyg1sAZOm9ReT9vIehjBgUO+NJjFrvAt41KPsMX8oNyadpbuzWgFXAG9fPa1bmFJKgYQzXBdmTp53WlcnDcBCHYpIucm0743UeGq673dSj1ywtjdRv6TM/7oJNAHOtvIIqPM8zf4sp4SJksVtZ/NAmgHtaUG1m1hgzUU2qouu23xUjUfwh2npDShi5vYSvJk1SLo7ybVWgGdipfpZQ/2ewScBXlXvh/g6Ib8hhxhLBU4NU+Rb4Zyjvf1/XmzFCFEusJH82nU5h+2Iieph7E8SmyHZjuoEHeQwE/1cIxrSyGLNE732E94mLzmWXPpzwNArmKcqUlZ1XqkeN3KXszXBj6pGhLYrQOds3G21WMCp+tcIZMkaDbR0NVGw23Sgcw8IcrSgkpg2BuLBKFRfGhm5yCApxWK3JviBiUPL2xolztsHYx3/B0xis7Mka+jwSMd6M+yYguUyfo5zCQNVYftSJhBF/ye4npRiqOIfIDRIIzjmYM8RUCrGcuK56X9d5ZFRpQm4fdhFhnLo=

language: node_js
node_js:
  - 10.14.2

services:
  - docker

cache:
  directories:
  - $HOME/.npm

notifications:
  email:
    on_failure: change
    on_success: change

install:
  - npm ci

script:
  - npm run lint:ci
  - npm run test:ci
  - npm run build:fosdem19:ssr:production
  - sh build-docker-fosdem19.sh
