env:
  global:
  - secure: DNJ+9FZ8/kxzSbryk1lPrYsmP1Tkzxt95xH5YXYLParSKP+y+wgTocaJS+pOGUaufwjSnalTxIE4EGU8FJTbsfA1MQfciSVu9VkbAicWdh6ijadU16eKaVB3pDkdBR5ABsWdX5PkqviYSlI3mSR9gQ7V+Czxij/2Om0YAOSJAyeMM1ntlg+iHPZo5TQWqnTuW33oUv/OoYM0LGMs9SqC/hOzLu6d8MqWokiVZJzYONOlLcILqtjN6o4B2yDcGMehULvR2ceO36u0wpXcvF0wCZtVYE80w5ub4LQ4up3JB15TGqPIqw7UtJoYd/zY78LSmljgUdAhS2QTPairZAwQ4DCdzDQkgyvkc6+ee5Y6sdRpy0OypRVW3+GehKaP+g1ipi0xGquF7LfpkcFCSUfzrJJ4SXLrDcIo/zLhtMOKIGH7ce4y2DzJOzaFXWIbBEgi1EeAFY6lNqH3eSBqV5omOyEiCTx2yFS6hMI6n3OsWPjICA2LFAg2mnHGjvehueWaRp3trvhNXAcYxSZZraibzNLWdR8x9/1LIvgn8y/NuK9Z/kTo9DZVrxXmDvMtqSL1+ookb6Gd1bJpJ2TRoVkEjGsUq9Xl/6ms7p4m1WNkfzJTbgh07DUtd+18lh/jF6UkPBS3zRzCNaS93ZOWuKPCYpya8TUAEtybwMXWj7fBwnM=
  - secure: VZwMiv3o74UFT1lfiu8NNEf3DL0MiexF5AAxNLCJpBKtGdY4zkkgC+m4lo48CKwSv0gWUVCL6+trKdGRYPCFl20malB2em/+Ee/EDf2FXRmELYvMXeuMIPcIMsDnjXQFhCwzcZjzUfm68XHKYznMtEt5zGijPnmyg1sAZOm9ReT9vIehjBgUO+NJjFrvAt41KPsMX8oNyadpbuzWgFXAG9fPa1bmFJKgYQzXBdmTp53WlcnDcBCHYpIucm0743UeGq673dSj1ywtjdRv6TM/7oJNAHOtvIIqPM8zf4sp4SJksVtZ/NAmgHtaUG1m1hgzUU2qouu23xUjUfwh2npDShi5vYSvJk1SLo7ybVWgGdipfpZQ/2ewScBXlXvh/g6Ib8hhxhLBU4NU+Rb4Zyjvf1/XmzFCFEusJH82nU5h+2Iieph7E8SmyHZjuoEHeQwE/1cIxrSyGLNE732E94mLzmWXPpzwNArmKcqUlZ1XqkeN3KXszXBj6pGhLYrQOds3G21WMCp+tcIZMkaDbR0NVGw23Sgcw8IcrSgkpg2BuLBKFRfGhm5yCApxWK3JviBiUPL2xolztsHYx3/B0xis7Mka+jwSMd6M+yYguUyfo5zCQNVYftSJhBF/ye4npRiqOIfIDRIIzjmYM8RUCrGcuK56X9d5ZFRpQm4fdhFhnLo=

branches:
  only:
    - master
    - ^pr

language: node_js
node_js:
  - 10.14.2

services:
  - docker

cache:
  directories:
  - $HOME/.npm

notifications:
  email:
    on_failure: change
    on_success: change

install:
  - npm ci

script:
  - npm run lint:ci
  - npm run test:ci
  - npm run build:fosdem19:ssr:production
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - sh build-docker-fosdem19.sh
